### ISSUE TITLE
支持的浏览器有哪些？

### ISSUE THREAD

**Issue by duanjiuzhou** [bingoogolapple/bga-back-top-vue#4]
想了解下，bga-back-top-vue对哪些浏览器支持，对ie浏览器的支持程度？谢谢哈~

**Comment by bingoogolapple** [comment]
我不是专业做前端开发的哈，这个开源库是我在做 [BGAIssueBlog](https://github.com/bingoogolapple/BGAIssueBlog) 时衍生的一个子库

## 目前 [Demo](http://www.bingoogolapple.cn/bga-back-top-vue) 只在如下浏览器测试通过

### Mac

- [x] Chrome 59.0.3071.115
- [x] Safari 10.1.1 (12603.2.4)
- [x] Firefox 54.0.1

### Windows

- [x] Chrome 59.0.3071.86
- [x] Firefox 53.0.3
- [x] IE 10、IE Edge （不考虑 Demo 用的 flexbox 布局的话，应该能兼容到 IE9 的）
- [x] 360 安全浏览器 版本：8.1.1.158、内核版本：45.0.2454.101

### iPhone 6 Plus - 10.3.2

- [x] Chrome
- [x] Safari

### Android

- [x] Nexus 5 - Android 6.x - Chrome
